[package]
name = "example-client"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
shah = { path = "../shah" }
example-db = { path = "../example-db" }
log = "0.4.22"

# [lints.rust]
# dead_code = "allow"
# unused = "allow"
