[package]
name = "example-db"
version = "9235.69.0"
edition.workspace = true
publish = false

[dependencies]
shah = { path = "../shah" }
log = "0.4.22"
rand = "0.8.5"

# [lints.rust]
# dead_code = "allow"
# unused = "allow"
